### ISSUE TITLE
-bash: kgctl: command not found

### ISSUE THREAD

**Issue by nitish2087** [squat/kilo#119]
It seems something went wrong while installation following up documentation. I have installed kilo for kubeadm with flannel for my kubernetes cluuster of 4 nodes(one master and three workers). A daemonset is running an instance of kilo on every node as well in kube-system namespace.
The problem i'm getting after it:

Add-on mode for kubeadm-flannel
$ kubectl apply -f https://github.com/squat/kilo/blob/master/manifests/kilo-kubeadm-flannel.yaml
error: error parsing https://github.com/squat/kilo/blob/master/manifests/kilo-kubeadm-flannel.yaml: error converting YAML to JSON: yaml: line 91: mapping values are not allowed in this context

Applying VPN
kind: Peer not found

I noticed kgctl tool is not working, resolving which may be the ultimate solution. Please tell me how to install it, it didn't get installed following doc.

**Comment by squat** [comment]
Hi @nitish2087 this error is coming up because the resource being applied is an HTML page and not a YAML manifest. The command you shared: `kubectl apply -f https://github.com/squat/kilo/blob/...` is not installing the actual manifest. Instead, you should apply apply the URL for the *raw* file, e.g.:
```shell
kubectl apply -f https://raw.githubusercontent.com/squat/kilo/master/manifests/kilo-kubeadm-flannel.yaml
```

The reason that `kgctl` is failing to find the `Peer` resource is because the kubectl command is failing, which fails to install Kilo on the cluster, which in turn means that the `Peer` CustomResource is never installed in the Kubernetes API.

Installing the Kilo manifest correctly should fix this issue.

**Comment by squat** [comment]
Note for instance that the example commands in https://github.com/squat/kilo#step-5-install-kilo all use URLs beginning with `https://raw.githubusercontent.com` rather than `https://github.com` Please let me know if you have any more questions.

**Comment by squat** [comment]
Closing this for now. Please reopen if you still have trouble @nitish2087!

**Comment by nitish2087** [comment]
Hii @squat, thanks a lot for your help and concerns till now. I have been successful in creating a kilo mesh.
```
     kilo-255rh                            1/1     Running   0          44m   <ip-worker-0>   worker0.sb   <none>           <none>
     kilo-nrv7b                            1/1     Running   0          44m   <ip-worker-1>   worker1.sb   <none>           <none>
     kilo-p2jfg                            1/1     Running   0          44m   <ip-worker-2>   worker2.sb   <none>           <none>
     kilo-s9v5z                            1/1     Running   0          44m   <ip-master>     master.sb    <none>           <none>
```
I was also able to add additional peers through ```peers.yaml``` having ```kind: Peer```. But I was unable to give it access to the cluster. I'm still getting ```-bash: kgctl: command not found```. Kindly help me here.
Further, if kilo-pods(agents) are successfully running on a kilo mesh at each node, is there a way i can use to verify that my packets(data) sent within cluster is encrypted ?
Thanks.

**Comment by squat** [comment]
Hi @nitish2087, how did you Install kgctl? Note that today the only way to install kgctl is by building it manually as described here: https://github.com/squat/kilo/blob/main/docs/kgctl.md#installation

The upcoming 0.2.0 release of Kilo will include pre-built binaries for most common platforms.

To verify that traffic is being sent over the WireGuard connection, one can open a session on one of the desired nodes, eg via SSH, and type `sudo wg kilo0`. This will show the statistics for the WireGuard interface on that node. You should see that the received and transmitted bytes are non-zero. If you want to convince yourself that traffic is being encrypted for a specific packet, you can use your favorite packet tracing utility, eg tcpdump, to verify that each packet destined for a node in another Kilo location results in a corresponding packet over the kilo0 interface. Note: not all traffic in a cluster is encrypted; to understand when Kilo encrypts traffic, consider reading the topology doc: https://github.com/squat/kilo/blob/main/docs/topology.md.

**Comment by nitish2087** [comment]
Hi @squat , thanks for your help. I was able to setup kilo and send the encrypted packets over it on the top of WireGuard.
I'm left with only one doubt for now i.e 
```If we have a cluster running on hosted service of EKS (Amazon), will Kilo work on this cluster ?```
It would be helpful if you clear this.
Thanks.
